version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: sanamed_db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: sanamed2
    ports:
      - "3308:3307"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sanamed_network

  administrador:
    build: ./administrador
    container_name: administrador_service
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=sanamed2
    ports:
      - "5001:5000"
    networks:
      - sanamed_network
    depends_on:
      - db

  home:
    build: ./home
    container_name: home_service
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=sanamed2
    ports:
      - "5000:5000"
    networks:
      - sanamed_network
    depends_on:
      - db

  paciente:
    build: ./paciente
    container_name: paciente_service
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=sanamed2
    ports:
      - "5002:5000"
    networks:
      - sanamed_network
    depends_on:
      - db

  profesional:
    build: ./profesional
    container_name: profesional_service
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DB=sanamed2
    ports:
      - "5003:5000"
    networks:
      - sanamed_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  sanamed_network:
