version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sanamed2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  administrador:
    build:
      context: ./administrador
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5001:5000"

  home:
    build: ./home
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5006:5000"
    volumes:
      - ./home:/usr/src/app
    environment:
      - FLASK_ENV=development

  paciente:
    build:
      context: ./paciente
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5002:5000"

  profesional:
    build:
      context: ./profesional
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5003:5000"

volumes:
  db_data:
